title: 김장훈의 블로그
description: 이것저것 
author: 김장훈
logo: forewalk.github.io/static/img/avatar.png
github: https://forewalk.github.io/
about: 엔지니어

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: 김장훈
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
